### ISSUE TITLE
POI Forms Plugin

### ISSUE THREAD

**Issue by ektrontek** [mesilat/poi-forms#1]
Dear Support Team, 
Would it be possible to install POI Forms Plugin in confluence 5.8.2 version? After I try, it failed , and it shown message as shown as below.
![incompatible](https://user-images.githubusercontent.com/19470763/34724512-07b189fa-f589-11e7-8fd2-7edf094dcca0.png)

**Comment by mesilat** [comment]
Hi, Anderson
 
The message does not mean that the plugin is not working, but rather that it was not tested with your version of Confluence. Try it, as I am 99 percent confident it will work as expected but I do not have a Confluence instance that old to test. Please let me know if it works for you so I could amend the compatibility record at Atlassian Marketplace and your "error" will be gone ;)

**Comment by mesilat** [comment]
Due to multiple issues with version 5.8.2 this issue cannot be resolved:
1) there is no class User2ContentRelationEntity thus not demo space can be created from the plugin
2) there is no Moment.js library to handle dates
